### PR TITLE
update manifests with latest releases

### PR DESCRIPTION
**Pull request by usamaahmadkhan**

### CODE REVIEW

**Comment by stakater-user** [comment]
@usamaahmadkhan Yikes! You better fix it before anyone else finds out! [Build 1](https://jenkins.release.stakater.com/job/stakater-lab/job/nordmart-prod-apps/job/PR-16/1/) has Failed!

**Comment by stakater-user** [comment]
@usamaahmadkhan Tests have been passed!

**Comment by stakater-user** [comment]
@usamaahmadkhan Tests have been passed!

**Comment by stakater-user** [comment]
@usamaahmadkhan Tests have been passed!

**Comment by stakater-user** [comment]
@usamaahmadkhan Tests have been passed!

**Comment by stakater-user** [comment]
@usamaahmadkhan Tests have been passed!

**Comment by stakater-user** [comment]
@usamaahmadkhan Tests have been passed!

**Review by kahootali — APPROVED** [review]

**Pull request merged**
